# Generated by Django 6.0.5 on 2026-06-28 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEnrollmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('mode', models.CharField(choices=[('REJECT_ALL', 'Reject entire file on any error (default)'), ('IMPORT_VALID', 'Import valid rows, skip invalid')], default='REJECT_ALL', max_length=15)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=12)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_enrollment_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
