# Generated by Django 6.0.5 on 2026-06-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bulkenrollmentjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEnrollmentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('row_start', models.PositiveIntegerField()),
                ('row_end', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Succeeded'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=10)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='accounts.bulkenrollmentjob')),
            ],
            options={
                'db_table': 'bulk_enrollment_chunks',
                'ordering': ['chunk_index'],
                'unique_together': {('job', 'chunk_index')},
            },
        ),
    ]
