# Generated by Django 6.0.5 on 2026-06-24 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='TimetableConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('VENUE_CONFLICT', 'Venue Conflict'), ('LECTURER_CONFLICT', 'Lecturer Conflict'), ('STUDENT_GROUP_CONFLICT', 'Student Group Conflict')], max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timetable_entry_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='timetable.timetableentry')),
                ('timetable_entry_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='timetable.timetableentry')),
            ],
            options={
                'db_table': 'timetable_conflicts',
                'ordering': ['-created_at'],
            },
        ),
    ]
