# Generated by Django 6.0.5 on 2026-06-25 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_semester_is_active_studentgroup_academic_year_and_more'),
        ('timetable', '0002_alter_timetableentry_status_timetableconflict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableconflict',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timetableconflict',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='TimetablePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_entries_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academics.academicyear')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_timetables', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academics.semester')),
            ],
            options={
                'db_table': 'timetable_publications',
                'ordering': ['-published_at'],
            },
        ),
    ]
