# Generated by Django 6.0.5 on 2026-06-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_phase8'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='confirmation_window_minutes',
            field=models.PositiveIntegerField(default=40, help_text='Minutes after start_time before an unconfirmed session expires.'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='reminder_lead_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Minutes before start_time to send a session reminder.'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='capacity_overhead',
            field=models.FloatField(default=1.5, help_text='Upper-bound multiplier. 100 students → venues up to 150 seats (1.5×).'),
        ),
    ]
