# Generated by Django 6.0.5 on 2026-06-28 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_srs33_system_config'),
        ('venues', '0007_rename_venues_status_idx_venues_status_fa03fe_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencysession',
            name='capacity_conflict',
            field=models.BooleanField(default=False, help_text='True when expected_students > venue.capacity.'),
        ),
        migrations.AddField(
            model_name='emergencysession',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional notes or instructions.'),
        ),
        migrations.AddField(
            model_name='emergencysession',
            name='expected_students',
            field=models.PositiveIntegerField(blank=True, help_text='Number of students expected to attend.', null=True),
        ),
        migrations.AddField(
            model_name='emergencysession',
            name='required_resources',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["projector","whiteboard"]'),
        ),
        migrations.AddField(
            model_name='emergencysession',
            name='title',
            field=models.CharField(blank=True, help_text='Short descriptive title, e.g. "Makeup Lab Session".', max_length=200),
        ),
        migrations.CreateModel(
            name='SessionPostponement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_date', models.DateField()),
                ('new_day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('new_start_time', models.TimeField()),
                ('new_end_time', models.TimeField()),
                ('reason', models.TextField()),
                ('postponed_at', models.DateTimeField(auto_now_add=True)),
                ('new_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_postponements', to='venues.venue')),
                ('original_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postponements', to='timetable.timetableentry')),
                ('postponed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postponed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_postponements',
                'ordering': ['-postponed_at'],
            },
        ),
    ]
