# Generated by Django 6.0.5 on 2026-06-28 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_srs34_emergency_fields_postponement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='confirmation_window_minutes',
            field=models.PositiveIntegerField(default=50, help_text='Minutes after start_time before an unconfirmed session expires. SRS default: 50.'),
        ),
        migrations.CreateModel(
            name='SessionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Calendar date of this specific occurrence.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired — No Confirmation Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_sessions', to=settings.AUTH_USER_MODEL)),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='timetable.timetableentry')),
            ],
            options={
                'db_table': 'session_confirmations',
                'ordering': ['-session_date', 'timetable_entry'],
                'unique_together': {('timetable_entry', 'session_date')},
            },
        ),
    ]
