# Generated by Django 6.0.5 on 2026-06-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_srs35_session_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='max_bulk_upload_rows',
            field=models.PositiveIntegerField(default=5000, help_text='Max rows in a single CSV upload. Default: 5000'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='password_reset_link_hours',
            field=models.PositiveIntegerField(default=48, help_text='Hours until a welcome/reset link expires. Default: 48'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='sms_bulk_approval_threshold',
            field=models.PositiveIntegerField(default=50, help_text='Recipients above which bulk SMS requires coordinator approval. Default: 50'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='sms_daily_cap_per_user',
            field=models.PositiveIntegerField(default=5, help_text='Maximum SMS messages a single user may receive per calendar day. Default: 5'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='venue_status_check_interval_seconds',
            field=models.PositiveIntegerField(default=60, help_text='How often Celery Beat checks for ended sessions (seconds). Default: 60'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='capacity_overhead',
            field=models.FloatField(default=1.5, help_text='Multiplier on expected_students for venue upper-bound. Default: 1.5'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='confirmation_window_minutes',
            field=models.PositiveIntegerField(default=40, help_text='Minutes after start_time within which lecturer must confirm. Default: 40'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='reminder_lead_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Minutes before start_time to send the pre-session reminder. Default: 120'),
        ),
    ]
