# Generated by Django 6.0.5 on 2026-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_srs311_system_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('NEEDS_REASSIGNMENT', 'Needs Reassignment'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
