# Generated by Django 6.0.5 on 2026-06-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buildings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('floor', models.IntegerField(default=0)),
                ('capacity', models.PositiveIntegerField()),
                ('venue_type', models.CharField(choices=[('LECTURE_HALL', 'Lecture Hall'), ('CLASSROOM', 'Classroom'), ('LABORATORY', 'Laboratory'), ('COMPUTER_LAB', 'Computer Lab'), ('SEMINAR_ROOM', 'Seminar Room'), ('AUDITORIUM', 'Auditorium')], max_length=20)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('accessibility', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('BOOKED', 'Booked'), ('IN_USE', 'In Use'), ('EXPIRED', 'Expired'), ('MAINTENANCE', 'Under Maintenance')], default='FREE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='venues.building')),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['building', 'code'],
            },
        ),
    ]
