# Generated by Django 6.0.5 on 2026-06-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_management_v2'),
        ('venues', '0003_seed_venue_coordinates'),
    ]

    operations = [
    ]
