# Generated by Django 6.0.5 on 2026-06-25 08:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_merge_20260625_0736'),
    ]

    operations = [
        # `code` was already added by 0002_venue_management_v2.
        # Use SeparateDatabaseAndState so Django records the state without
        # touching the DB (avoids DuplicateColumn on a populated database).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='building',
                    name='code',
                    field=models.CharField(
                        max_length=20, unique=True, null=True, blank=True,
                    ),
                ),
            ],
            database_operations=[],  # column already exists — nothing to do
        ),
    ]
