# Generated by Django 6.0.5 on 2026-06-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_add_building_code'),
    ]

    operations = [
    ]
