# Generated by Django 6.0.5 on 2026-06-25 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_add_building_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='venue',
            new_name='venues_status_fa03fe_idx',
            old_name='venues_status_idx',
        ),
        migrations.RenameIndex(
            model_name='venue',
            new_name='venues_venue_t_e71370_idx',
            old_name='venues_type_idx',
        ),
        migrations.RenameIndex(
            model_name='venue',
            new_name='venues_is_acti_c229c0_idx',
            old_name='venues_active_status_idx',
        ),
        migrations.RenameIndex(
            model_name='venue',
            new_name='venues_buildin_7a1a33_idx',
            old_name='venues_bldg_floor_idx',
        ),
        migrations.RenameIndex(
            model_name='venuestatushistory',
            new_name='venue_statu_venue_i_9f64e2_idx',
            old_name='vsh_venue_chg_idx',
        ),
        migrations.RenameIndex(
            model_name='venuestatushistory',
            new_name='venue_statu_trigger_bf113e_idx',
            old_name='vsh_event_idx',
        ),
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(blank=True, help_text='Short code, e.g. "COICT", "ECT", "LIB-A". Used as the human-readable identifier on the map.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Entry-point latitude (WGS84).', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Entry-point longitude (WGS84).', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='floor',
            field=models.IntegerField(default=0, help_text='Floor number. 0 = ground floor; basements are negative.'),
        ),
        migrations.AlterField(
            model_name='venuestatushistory',
            name='triggered_by_event',
            field=models.CharField(choices=[('TIMETABLE_ENTRY_CREATED', 'Timetable entry created'), ('EMERGENCY_SESSION_APPROVED', 'Emergency session approved'), ('LECTURER_CONFIRMED', 'Lecturer confirmed session'), ('CONFIRMATION_WINDOW_EXPIRED', 'Confirmation window expired'), ('SESSION_CANCELLED', 'Session cancelled'), ('SESSION_ENDED', 'Session reached end_time'), ('AUTO_RELEASE', 'Auto-released after expiry'), ('MAINTENANCE_STARTED', 'Maintenance started'), ('MAINTENANCE_ENDED', 'Maintenance ended'), ('MANUAL_OVERRIDE', 'Manual override by administrator'), ('SEEDED', 'Initial state set during data seeding')], help_text='Coarse-grained event category that drove the transition.', max_length=50),
        ),
        migrations.AlterField(
            model_name='venuestatushistory',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, help_text='User who initiated the transition. Null for system-driven transitions (e.g. Celery Beat expiry checks).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_status_transitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
