# Generated by Django 6.0.5 on 2026-06-28 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EMERGENCY_CREATED', 'Emergency Session Created'), ('EMERGENCY_APPROVED', 'Emergency Session Approved'), ('EMERGENCY_REJECTED', 'Emergency Session Rejected'), ('SESSION_CONFIRMED', 'Session Confirmed'), ('SESSION_POSTPONED', 'Session Postponed'), ('SESSION_CANCELLED', 'Session Cancelled'), ('SESSION_EXPIRED', 'Session Expired'), ('TIMETABLE_UPDATED', 'Timetable Updated'), ('VENUE_CHANGED', 'Venue Changed'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
        migrations.CreateModel(
            name='BulkSMSJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200)),
                ('notification_type', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recipient_count', models.PositiveIntegerField()),
                ('recipients_json', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting Coordinator Approval'), ('APPROVED', 'Approved — dispatching'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched')], default='PENDING', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_sms_jobs',
            },
        ),
        migrations.CreateModel(
            name='SMSRetryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('event_id', models.CharField(blank=True, max_length=200)),
                ('notification_type', models.CharField(blank=True, max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RETRYING', 'Retrying'), ('SENT', 'Sent'), ('FAILED', 'Failed (max retries exceeded)'), ('FALLEN_BACK', 'Fallen back to push/in-app')], default='PENDING', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_retry_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_retry_jobs',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('fcm_token', models.CharField(blank=True, max_length=500)),
                ('notify_timetable_changes', models.BooleanField(default=True)),
                ('notify_venue_changes', models.BooleanField(default=True)),
                ('notify_emergency_sessions', models.BooleanField(default=True)),
                ('notify_session_confirmation', models.BooleanField(default=True)),
                ('notify_session_postponement', models.BooleanField(default=True)),
                ('notify_session_cancellation', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=10)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_log',
                'unique_together': {('event_id', 'recipient_user', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='SMSDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_daily_log',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
