# Generated by Django 6.0.5 on 2026-06-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_groups', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='student_count',
            field=models.PositiveIntegerField(default=0, help_text='Expected number of students in this group. Used by the timetable generator for venue capacity matching.'),
        ),
        migrations.CreateModel(
            name='TeachingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, help_text='Optional human-readable label, e.g. "Period 1". Auto-generated from day + time if left blank.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive periods are excluded from timetable generation.')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_periods', to='academics.semester')),
            ],
            options={
                'db_table': 'teaching_periods',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('semester', 'day_of_week', 'start_time')},
            },
        ),
    ]
